name: Create release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  contents: write # Grant write permissions to the GITHUB_TOKEN

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get a new tag based on latest tag
        id: version
        run: echo "version=$(git tag --merged HEAD |  tail -1 | perl -pe 's/(.*)(\d+)/$1.($2+1)/e')" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          TAG: ${{ steps.version.outputs.version }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} $TAG" \
            --generate-notes # Automatically generate release notes
