name: Create release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  contents: write

jobs:
  tag_release:
    runs-on: ubuntu-latest
    outputs:
      GITTAGVER: ${{ steps.set_version.outputs.GITTAGVER }}
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: set_version
        name: Set tag version and apply tag
        run: |
          tmpversion="$(./scripts/tag_latest_commit.sh)"
          echo "GITTAGVER=$tmpversion" >> "$GITHUB_OUTPUT"
          echo "Computed GITTAGVER=$tmpversion"
  release:
    runs-on: ubuntu-latest
    needs: tag_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Create release
        env:          
          TAG: ${{ needs.tag_release.outputs.GITTAGVER }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "releasing version $TAG $TAG"
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} $TAG" \
            --generate-notes
