name: Create release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  contents: write # Grant write permissions to the GITHUB_TOKEN

jobs:
  tag_release:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set_version.outputs.VERSION }}
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4
      - id: set_version
        name: Set tag version and apply tag
        run: echo "VERSION=$(./scripts/tag_latest_commit.sh)" >> $GITHUB_OUTPUT
  release:
    runs-on: ubuntu-latest
    needs: tag_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create release
        env:          
          TAG: ${{ needs.tag_release.outputs.VERSION }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} $TAG" \
            --generate-notes # Automatically generate release notes
