name: Create release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  contents: write # Grant write permissions to the GITHUB_TOKEN

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variable
        id: set_version
        run: echo "VERSION=$(./scripts/tag_latest_commit.sh)" >> $GITHUB_ENV
      - name: Create release
        env:
          TAG: ${{ steps.set_version.outputs.VERSION }}
          GH_TOKEN: ${{ github.token }}
        run: echo "$TAG"
